language: java
sudo: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2/repository
notifications:
  email: true
env:
  global:
	secure: "Djs06+Hm+oL/Niai2vZIJVkECNuORLYJ+48/f1BzU1CRQGmEkuBspSNSzpvf8tQlm8JWILG2GhMaLpo8U/QnyYENnlY0R56zHcd1NqcIITMpf7TZAspFZoDvlB9EFqEjKrmELsWvF5uyejF2Aebs+SueKDuxClaTcghOXXA1nvo95dsWl2OgZpN4gVMNKth/gtMPvEN4KB4VnC0nNwHMd/9TfPv3cVlhy6qrCzhMT8toNdkWoWRh1vUC2f5NuzuUfoTz0GltZvqXZRy97j1j1PwfIZOS1ybNx2ZajMX+64j7lGpvw7+hSWnE6FEjW71tNSnaAPuPjF5PAyXGsRaUIyT5kY+7MOO1fzrxcuPm3gqUv6hookhLoUYDcE8AHqdAsk5HvTqN9WjOhJ7rY8vAfzw7MKyx1F86jMx4U+9GqGZ8+plcj8f80gkjG8XVlyr8gMZqRpl5vFWo+sRKPtba/HaF/8VEZ3cwpgtYcGqrXTxGCgmx1VmmUgj4/PzaoDZ75ixwtzjXfK2ECLVvwj62nUdkDAkDyi2iCGzFsxYs6FMzPipaFjXQyMEFuzhkVeTZRzmWl0CIaUZ4ha959wNbdZIzj9FAEsoY89JbNH/HlER9sEcOJEh/czay3gAio5pxKqc2DjHP97acWXAwqv/PEPiAyHLnhG77O24Tfx+roHk="
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
